// Code generated by scripts/schemas; DO NOT EDIT.
package main

import (
	"metavida/backend/db"
	"metavida/backend/security"
)

func MakeDeploySchemas() []db.TableDeployInterface {
	return []db.TableDeployInterface{
		db.Table[security.User](),
	}
}
